on:
  push:
    tags:
      - "v*"
env:
  PROPERTIES_PATH: "./android/key.properties"

name: "Build & Release"
jobs:
  build-mobile:
    name: Build & Release Mobile
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Creating the key.properties file
      - run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}

      # Decoding base64 key into a file
      - run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/key.jks

      # Get dependencies and make assigned appbundle
      - run: |
          flutter pub get
          flutter build appbundle

      # build apk
      - run: flutter build apk --split-per-abi

      # push to releases
      - name: Push to Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        with:
          files: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-windows:
    name: Build & Release Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart fix --apply
      - run: flutter pub get
      # build msix
      - name: Build artifacts
        run: dart run msix:create
      # push to releases
      - name: Push to Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        with:
          files: build/windows/x64/runner/Release/flipnmatch.msix
